# Generated by Django 4.1.4 on 2023-05-15 14:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dining', '0028_alter_dininglist_payment_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dininglist',
            name='adjustable_duration',
            field=models.DurationField(
                default=datetime.timedelta(days=14), help_text='How long the dining list can be adjusted after its date.'
            ),
        ),
        migrations.CreateModel(
            name='PaymentConfirmationRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateTimeField()),
                ('message', models.TextField()),
                ('type', models.TextField()),
                ('accepted', models.BooleanField()),
                ('accepted_date', models.DateTimeField()),
                (
                    'accepted_person',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='received_payment_update_requests',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ('dining_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dining.diningentry')),
                (
                    'requesting_user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='sent_payment_update_requests',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
